source setvars

$REXEC CMD BATCH --vanilla "--args GSE12418 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE12418_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE12470 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE12470_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE13876 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE13876_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE14764 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE14764_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE17260 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE17260_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE18520 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE18520_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE19161 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE19161_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE26712 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE26712_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE6008 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE6008_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE6822 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE6822_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE8842 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE8842_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE9891 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE9891_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE19829 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE19829_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE20565 $DATAHOME GPL570" $SRCHOME/gse_PROCESSED.R $LOG/GSE20565_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE32062 $DATAHOME GPL6480" $SRCHOME/gse_PROCESSED.R $LOG/GSE32062-GPL6480_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE32063 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE32063_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE30009 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE30009_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE30161 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE30161_downloadPROCESSED.log
./download_E-MTAB-386
./download_TCGA-mirna-8x15kv2.sh


# # $REXEC CMD BATCH --vanilla "--args GSE18154 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE18154_downloadPROCESSED.log
# # $REXEC CMD BATCH --vanilla "--args GSE3149 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE3149_downloadPROCESSED.log
# # $REXEC CMD BATCH --vanilla "--args GSE8841 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE8841_downloadPROCESSED.log
# # $REXEC CMD BATCH --vanilla "--args GSE7463 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE7463_downloadPROCESSED.log
# # $REXEC CMD BATCH --vanilla "--args GSE17260 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE17260_downloadPROCESSED.log
