source setvars

$REXEC CMD BATCH --vanilla "--args GSE17260 $DATAHOME" $SRCHOME/QC.R $LOG/GSE17260_QC.log
$REXEC CMD BATCH --vanilla "--args GSE18520 $DATAHOME" $SRCHOME/QC.R $LOG/GSE18520_QC.log
$REXEC CMD BATCH --vanilla "--args GSE18154 $DATAHOME" $SRCHOME/QC.R $LOG/GSE18154_QC.log
$REXEC CMD BATCH --vanilla "--args GSE26712 $DATAHOME" $SRCHOME/QC.R $LOG/GSE26712_QC.log
$REXEC CMD BATCH --vanilla "--args GSE3149 $DATAHOME" $SRCHOME/QC.R $LOG/GSE3149_QC.log
$REXEC CMD BATCH --vanilla "--args GSE8841 $DATAHOME" $SRCHOME/QC.R $LOG/GSE8841_QC.log
$REXEC CMD BATCH --vanilla "--args GSE8842 $DATAHOME" $SRCHOME/QC.R $LOG/GSE8842_QC.log
$REXEC CMD BATCH --vanilla "--args GSE12470 $DATAHOME" $SRCHOME/QC.R $LOG/GSE12470_QC.log
$REXEC CMD BATCH --vanilla "--args GSE13876 $DATAHOME" $SRCHOME/QC.R $LOG/GSE13876_QC.log
$REXEC CMD BATCH --vanilla "--args GSE20565 $DATAHOME" $SRCHOME/QC.R $LOG/GSE20565_QC.log
$REXEC CMD BATCH --vanilla "--args GSE7463 $DATAHOME" $SRCHOME/QC.R $LOG/GSE7463_QC.log
$REXEC CMD BATCH --vanilla "--args GSE6008 $DATAHOME" $SRCHOME/QC.R $LOG/GSE6008_QC.log
$REXEC CMD BATCH --vanilla "--args GSE12418 $DATAHOME" $SRCHOME/QC.R $LOG/GSE12418_QC.log
$REXEC CMD BATCH --vanilla "--args GSE17260 $DATAHOME" $SRCHOME/QC.R $LOG/GSE17260_QC.log
$REXEC CMD BATCH --vanilla "--args GSE6822 $DATAHOME" $SRCHOME/QC.R $LOG/GSE6822_QC.log
$REXEC CMD BATCH --vanilla "--args GSE9891 $DATAHOME" $SRCHOME/QC.R $LOG/GSE9891_QC.log
$REXEC CMD BATCH --vanilla "--args GSE20565 $DATAHOME" $SRCHOME/QC.R $LOG/GSE20565_QC.log
$REXEC CMD BATCH --vanilla "--args TCGA $DATAHOME" $SRCHOME/QC.R $LOG/TCGA_QC.log

#  Too many arrays for QC (expo dataset, many cancers, 2000+ arrays):
# #$REXEC CMD BATCH --vanilla "--args GSE2109 $DATAHOME" $SRCHOME/QC.R $LOG/GSE2109_QC.log
