source setvars

$REXEC CMD BATCH --vanilla "--args GSE1827 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE1827_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE19915 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE19915_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE13507 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE13507_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE89 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE89_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE5287 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE5287_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE31684 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE31684_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE32894 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE32894_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE31189 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE31189_downloadPROCESSED.log
$REXEC CMD BATCH --vanilla "--args GSE37317 $DATAHOME" $SRCHOME/gse_PROCESSED.R $LOG/GSE37317_downloadPROCESSED.log
